### PR TITLE
Bool vectors!

### LINKED ISSUE #36: bvecN types have wrong representation
GLSL's bools are 32 bits. Rust's are 8 bits. Making a vec of 8 bit bools doesn't make them line up.

Additionally, I don't think `bool` is fully inhabited, so making it `Pod`/`Zeroable` isn't quite right.

### PR DESCRIPTION
**Pull request by ElectronicRU**
Closes #36 .

### CODE REVIEW

File: src/std430/primitives.rs [hunk 1]
```diff
@@ -1,7 +1,8 @@
 use bytemuck::{Pod, Zeroable};
+use crate::bool::GlslBoolean;
 
 use crate::glsl::Glsl;
-use crate::std430::Std430;
+use crate::std430::{AsStd430, Std430};
```
Comment (LPGhatguy) [inline src/std430/primitives.rs:5]: Can you group these imports together instead of leaving a lonely `use crate` up there with bytemuck?

I noticed this in another file or two as well

**Review by LPGhatguy — COMMENTED** [review]
Style nit, then LGTM!

Thanks for the contribution, this is a nice one.

**Comment by LPGhatguy** [comment]
Oh, actually, this would be good to write a test or two for.

**Review by LPGhatguy — APPROVED** [review]
